language: python

python:
  - 3.7

script:
  - pip install file://$(pwd)

deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist bdist_wheel"
  password:
    secure: AL+tApxx53LfJvfrjIlFZp1UcZhRnzGM7mpvYU8zMqE8JNoFJMM6oeNy6o85xG1O+8Xmp5QsNh0xUDht+6RhGS+qW6b5lIo4TJtYZTy0CJy5ebOaEHow5v2tAZeRj7+nnqqHH8ecUtQ3lPA8DyR6Yi1uPOVW/lyHBOg9MhoaqeM=
  on:
    tags: true
    repo: pyblish/pyblish-3dsmax
